### ISSUE TITLE
> tmp_out | echo 1

### ISSUE THREAD

**Issue by PaulicStudios** [JonasGoetz01/42-minishell#207]
```
>tmp_out | echo 1
Tokens:
Type: 5, Value: >
Type: 0, Value: tmp_out
Type: 15, Value:  
Type: 8, Value: |
Type: 15, Value:  
Type: 0, Value: echo
Type: 15, Value:  
Type: 0, Value: 1
Tokens:
Type: 5, Value: >
Type: 0, Value: tmp_out
Type: 15, Value:  
Type: 8, Value: |
Type: 15, Value:  
Type: 0, Value: echo
Type: 15, Value:  
Type: 0, Value: 1
Tokens:
Type: 5, Value: >
Type: 0, Value: tmp_out
Type: 8, Value: |
Type: 0, Value: echo
Type: 15, Value:  
Type: 0, Value: 1
Tokens:
Type: 5, Value: >
Type: 0, Value: tmp_out
Type: 8, Value: |
Type: 0, Value: echo
Type: 15, Value:  
Type: 0, Value: 1
Input is valid
Tokens:
Type: 5, Value: >
Type: 0, Value: tmp_out
Type: 8, Value: |
Type: 0, Value: echo
Type: 15, Value:  
Type: 0, Value: 1
Highest token: |
Highest Bracket Level: 0
Highest token: >
Highest Bracket Level: 0
Highest token: 
Highest Bracket Level: 0
Highest token: tmp_out
Highest Bracket Level: 0
Highest token: 1
Highest Bracket Level: 0
    Type: 13, Value: echo Prio: -1
    Type: 15, Value:   Prio: -1
    Type: 14, Value: 1 Prio: -1
Type: 8, Value: | Prio: 3
        Type: 14, Value: tmp_out Prio: -1
    Type: 5, Value: > Prio: 2
        Type: 15, Value:  Prio: -1
executing echo: in 3 out -1
 1
waiting for echo...
AddressSanitizer:DEADLYSIGNAL
=================================================================
==14089==ERROR: AddressSanitizer: SEGV on unknown address 0x55e617b7ccf0 (pc 0x7fcee5dd8532 bp 0x55e617b7cd00 sp 0x7ffdfa2e7be0 T0)
==14089==The signal is caused by a WRITE memory access.
    #0 0x7fcee5dd8532 in bool __sanitizer::atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t>(__sanitizer::atomic_uint8_t volatile*, __sanitizer::atomic_uint8_t::Type*, __sanitizer::atomic_uint8_t::Type, __sanitizer::memory_order) ../../../../src/libsanitizer/sanitizer_common/sanitizer_atomic_clang.h:80
    #1 0x7fcee5dd8532 in __asan::Allocator::AtomicallySetQuarantineFlagIfAllocated(__asan::AsanChunk*, void*, __sanitizer::BufferedStackTrace*) ../../../../src/libsanitizer/asan/asan_allocator.cpp:570
    #2 0x7fcee5dd8532 in __asan::Allocator::Deallocate(void*, unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) ../../../../src/libsanitizer/asan/asan_allocator.cpp:647
    #3 0x7fcee5dd8532 in __asan::asan_free(void*, __sanitizer::BufferedStackTrace*, __asan::AllocType) ../../../../src/libsanitizer/asan/asan_allocator.cpp:883
    #4 0x7fcee5e59b43 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:128
    #5 0x55e617b72f1b in free_tokens src/input_parsing/token_utils.c:38
    #6 0x55e617b79196 in ft_free_nodes src/utils/cleanup.c:19
    #7 0x55e617b790fe in ft_free_nodes src/utils/cleanup.c:16
    #8 0x55e617b790fe in ft_free_nodes src/utils/cleanup.c:16
    #9 0x55e617b70c0b in process_input src/prompt/prompt.c:35
    #10 0x55e617b70f5f in show_prompt src/prompt/prompt.c:137
    #11 0x55e617b6e671 in main src/main.c:51
    #12 0x7fcee5ba8d09 in __libc_start_main ../csu/libc-start.c:308
    #13 0x55e617b6e379 in _start (/workspaces/42-minishell/minishell+0x4379)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../../../../src/libsanitizer/sanitizer_common/sanitizer_atomic_clang.h:80 in bool __sanitizer::atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t>(__sanitizer::atomic_uint8_t volatile*, __sanitizer::atomic_uint8_t::Type*, __sanitizer::atomic_uint8_t::Type, __sanitizer::memory_order)
==14089==ABORTING
```

**Comment by PaulicStudios** [comment]
@JonasGoetz01 help
Weißt du irgendwo zwei Notes die selben tokens zu, dass ein double free entsteht?

**Comment by JonasGoetz01** [comment]
ne kenne das problem. Ich habe gesagt, dass wenn es keinen linken arm gibt ein linker arm nur mit einem Space gemacht wird. Da gab es dann aber ein problem beim ast. Hab das jetzt gefixt. Wenn kein ast existiert wird auch keiner erstellt und der rekursive algo bricht einfach ab, sobald ein ast NULL ist.
