### ISSUE TITLE
segfault on mac

### ISSUE THREAD

**Issue by PaulicStudios** [JonasGoetz01/42-minishell#295]
```
/Users/pgrossma/Documents/projects/minishell ❯ >> "$H"OM"E"
Tokens:
Type: 6, Value: >>
Type: 15, Value:
Type: 11, Value: "
Type: 0, Value: $H
Type: 11, Value: "
Type: 0, Value: OM
Type: 11, Value: "
Type: 0, Value: E
Type: 11, Value: "
Tokens:
Type: 6, Value: >>
Type: 15, Value:
Type: 11, Value: "
Type: 0, Value:
Type: 11, Value: "
Type: 0, Value: OM
Type: 11, Value: "
Type: 0, Value: E
Type: 11, Value: "
Tokens:
Type: 6, Value: >>
Type: 15, Value:
Type: 11, Value: "
Type: 0, Value:
Type: 11, Value: "
Type: 0, Value: OM
Type: 11, Value: "
Type: 0, Value: E
Type: 11, Value: "
AddressSanitizer:DEADLYSIGNAL
=================================================================
==84193==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x0001011b86e4 bp 0x7ffeeea56610 sp 0x7ffeeea565e0 T0)
==84193==The signal is caused by a READ memory access.
==84193==Hint: address points to the zero page.
    #0 0x1011b86e4 in get_file rearrange_tokens.c
    #1 0x1011b8da5 in rearrange_tokens rearrange_tokens.c:104
    #2 0x1011af021 in process_input prompt.c:24
    #3 0x1011af4d5 in ft_execute_input prompt.c:78
    #4 0x1011af2e8 in show_prompt prompt.c:111
    #5 0x1011acb27 in main main.c:52
    #6 0x7fff69d5ccc8 in start+0x0 (libdyld.dylib:x86_64+0x1acc8)

==84193==Register values:
rax = 0x0000100000000002  rbx = 0x00001fffddd4acca  rcx = 0x0000000000000005  rdx = 0x0000000000000006
rdi = 0x0000000000000010  rsi = 0x0000000102b340e0  rbp = 0x00007ffeeea56610  rsp = 0x00007ffeeea565e0
 r8 = 0x0000000000000020   r9 = 0x0000000000000000  r10 = 0xffffffffffffffff  r11 = 0x00000fffffffffff
r12 = 0x0000100000000000  r13 = 0x00007ffeeea56650  r14 = 0x00007ffeeea56690  r15 = 0x00001fffddd4acd2
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV rearrange_tokens.c in get_file
==84193==ABORTING
[1]    84193 abort      ./minishell
```

**Comment by PaulicStudios** [comment]
kann mit`-g3 -Wall -Wextra -Wconversion -Wdouble-promotion
     -Wno-unused-parameter -Wno-unused-function -Wno-sign-conversion
     -fsanitize=undefined -fsanitize-trap` flags auf linux auch passieren
